forge "https://forgeapi.puppetlabs.com"

mod 'epics_gateway',
  :git => 'https://konrad@stash.frib.msu.edu/scm/deploy/puppet_module_epics_gateway.git'

mod 'epics_softioc',
  :git => 'https://stash.frib.msu.edu/scm/deploy/puppet_module_epics_softioc.git'

mod 'puppetlabs/apt'

mod 'puppetlabs/vcsrepo'